### ISSUE TITLE
SDMX Georeferencing

### ISSUE THREAD

**Issue by DrJMunozMx** [sdmx3mdt/public-consultation#1]
Georeferencing has been included in the technical notes inside the Codelists section (number 6), I think that this is not correct because codelist is only the third of the options to include geographical information into SDMX flows, first and second options are not related to codelists. The proposal is to put georeferencing into a new separated section.

**Comment by sdmx3mdt** [comment]
Change made by Stratos Nikoloutsos in Section 6 WORKING DRAFT 1.1.
https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EcWniXb0hXBMpYzDJqumqNIBnI24TkkbX36TZ0Zv31VRkg?e=qBJE1a
