### ISSUE TITLE
Remove leftover "MeasureDimension" constructs

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#10]
Since MeasureDimension has been removed there should be a complete cleanup of remaining related constructs, e.g.:

- "SingleMeasureDimension" constraint in "DimensionList"
- Many references to "MeasureDimension" in numerous XML documentations
- In schemas/SDMXCommon.xsd and in schemas/SDMXCommonReferences.xsd remove "MeasureDimension" from: "DimensionTypeType", "ObjectTypeCodelistType", "ComponentTypeCodelistType", "DataStructureComponentTypeCodelistType", "DimensionTypeCodelistType", "ObjectTypeListType".

Also remove "MeasureDimensionReferenceType", "MeasureDimensionRefType", "MeasureDimension" (empty type).

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
