### ISSUE TITLE
Remove "non-measure" from description of SimpleDataStructureRepresentationType

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#12]
Instead of "defines the representation for any non-measure and non-time dimension" it should be: "defines the representation for any non-time dimension"

But even "non-time dimension" is strange because TimeDimensionRepresentationType actually derives from SimpleDataStructureRepresentationType.

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
