### ISSUE TITLE
Improve RegEx for SemanticVersionReferenceType

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#22]
Instead of `((0|[1-9]\d*)\+?)(\.((0|[1-9]\d*)\+?)){2}` I would proposing using: `(^(0|[1-9]\d*)\+\.(0|[1-9]\d*)\.(0|[1-9]\d*)$)|(^(0|[1-9]\d*)\.(0|[1-9]\d*)\+\.(0|[1-9]\d*)$)|(^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)\+$)`.

The longer but more precise RegEx **_only_** allows for the wildcarding of **_one of_** the major, minor, or patch version parts using '+'. The description of that type should actually be updated in this sense.

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Decision: agreement that this change should be made in the XML schemas subject to advise from J Gager on the technical feasibility and generally whether it's sensible.
Action: J Gager to advise

**Comment by sdmx3mdt** [comment]
J Gager advice:
In XML schema, you can specify multiple patterns. 
This accomplishes the goal and is easier to understand in my opinion:
`<xs:restriction base="xs:string"> 
<xs:pattern value="((0|[1-9]\d*)\+?)(\.((0|[1-9]\d*))){2}"/> 
<xs:pattern value="((0|[1-9]\d*))(\.((0|[1-9]\d*)\+?))(\.((0|[1-9]\d*)))"/> 
<xs:pattern value="((0|[1-9]\d*)\+?)(\.((0|[1-9]\d*)))(\.((0|[1-9]\d*)\+?))"/> 
</xs:restriction>`

@dosse do you agree?

**Comment by dosse** [comment]
@sdmx3mdt Yes, it's fine as long as it corrects the current issue of possible multiple version wildcards. Please use the format that you see fits best in the context of xml.

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
