### ISSUE TITLE
Clarify/remove variances in URN class name lists

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#24]
The list of URN class names is different between the "[SDMX STANDARDS: SECTION 5 SDMX REGISTRY SPECIFICATION](https://metatechltd.sharepoint.com/:w:/s/SDMX30TechnicalSpecifications/EX9q-3Weh3ZDkt8K9TCxpkUBkpaC9V1fwqbeZ82DHudK_A?rtime=zA9-INAU2Ug)" (pages 31-33) and the class names listed in the "ObjectTypeCodelistType" type (in schemas/SDMXCommonReferences.xsd) used for the classes in the "WildcardObjectRefType" type.

The document doesn't have:
- Any
- Constraint
- DefinitionScheme
- ItemSchemeMap (are abstract classes allowed here?)
- MeasureDimension (this should have been removed)
- MetadataSet
- MetadataTarget (this should have been removed)
- Organisation
- OrganisationScheme
- ReportingYearStartDay
- VtlMapping

The document wrongly has: 
- IdentifiableObjectTarget --> shouldn't this be removed?
- ItemMap --> shouldn't this be removed?

Vice-versa, the "WildcardObjectRefType" type doesn't have:
- DataAttribute
- Subscription
- CodelistMap
- VtlCodelistMapping
- VtlConceptMapping
- VtlDataflowMapping

The type wrongly has:
- Attribute --> should be DataAttribute
- ItemSchemeMap (if abstract classes aren't allowed here)

Both wrongly have:
- ReportStructure --> shouldn't this be replaced by MetadataAttributeDescriptor?

Both seem missing:
- ReportingYearStartDay

Could it please be clarified what the correct class names are?

Also many other types in schemas/SDMXCommonReferences.xsd, many type wrongly use "Attribute" instead of "Data Atrribute".

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Action: Stratos Nikoloutsos and J Gager to agree on a definitive list of URN class names and to update both Section 5 and the XML Schemas.

**Comment by sdmx3mdt** [comment]
URN specifications clarified in Section 5 and schemas updated to comply with that specification.

The 02 September 2021 TWG decision to change the version element of the URN to (*) for versionless artefacts (e.g. Agency schemes) was reversed by mutual agreement through email exchange after technical problems were discovered - specifically conflict of the '*' character with other meanings in the REST API. For SDMX 3.0, the version element of the URN for such artefacts remains fixed at (1.0) which is consistent with the approach used for SDMX 2.1.
