### ISSUE TITLE
Type of agencyID in WildcardObjectRefType

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#25]
In schemas/SDMXCommonReferences.xsd:

Shouldn't the `agencyID` in `WildcardObjectRefType`/`WildcardRefBaseType` be based on a (wildcardable) `NestedNCNameIDType` type rather than a (wildcardable) `NestedIDType`?

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
