### ISSUE TITLE
Correct descriptions of MetadataStructureComponentsType (remove "a full target identifier") and MetadataProvisionAgreementType

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#26]
Replace last sentence by: "At a minimum, at least one metadata attribute must be defined."

Remove the data part from MetadataProvisionAgreementType, and mention metadata flow and metadata providers.

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
