### ISSUE TITLE
Improve validation capacity by using a pattern for WildcardedMemberValue (CodelistExtension)

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#27]
I would suggest the pattern `^[A-Za-z0-9_@$-]+%?$` (which is the IDType pattern extended with `%?` for wildcarding).
Also MemberValueType should be based on the IDType type rather than being a simple string in order to improve the validation capacity.

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
