### ISSUE TITLE
In schemas/SDMXStructureStructureMappings.xsd remove "ResolvePeriodType" since not used

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#32]

**Comment by sdmx3mdt** [comment]
Action with TF2 to review and update the Structure Mapping model which is out of date in Section 2.

**Comment by sdmx3mdt** [comment]
Investigation reveals that ResolvePeriod is still required but is missing from DateMapType.
Action to correct DateMapType.

**Comment by sdmx3mdt** [comment]
Added missing ResolvePeriod to DateMapType.
