### ISSUE TITLE
Correct HierarchicalCodeType documentation

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#35]
The HierarchicalCodeType XML documentation still wrongly states: "A hierarchical code provides for a reference to a code that is referenced within the hierarchical code list via ... a local reference which utilizes the included codelist reference alias and the identification of a code from the list"

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
