### ISSUE TITLE
Clarify how many TimeDimensions a DSD may have

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#36]
There are contradicting pieces of information about the allowed number of time dimensions in a DSD:

- in "DimensionListType", the "TimeDimension" is maxOccurs="unbounded"
- "TimeDimensionType" XML documentation: " The time dimension takes its semantic from its concept identity (usually the TIME_PERIOD concept), yet is always has a fixed identifier (TIME_PERIOD)." If there could be several time dimensions then there would be clash of the IDs that would not be unique.
- "type" attribute of "BaseDimensionType" XML documentation: "... this attribute allows ... maintaining the restriction of _only one_ measure and _time dimension_ while still allowing dimension to occur in any order."

If there can only be one TimeDimension, then this should be imposed by the schema. Also note that users have claimed the possibility of using several TimeDimensions within one DSD.

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Decision: DSDs should continue to support only one time dimension.

**Comment by sdmx3mdt** [comment]
No impact on the Information Model.
Section 2 DRAFT 1.0 is correct and states at line 1345
There can be a maximum of one TimeDimension specified in the DimensionDescriptor.

**Comment by sdmx3mdt** [comment]
Advice from J Gager:
While the schema structure for dimension list
```
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Dimension"/>
					<xs:element ref="TimeDimension"/>
				</xs:choice>
```
might appear to allow for unbounded time dimensions, the component uniqueness constraint prevents this. It is necessary to do it this way in order to allow for the time dimension to be positioned anywhere in the dimension key. So no change is needed.

However, in reviewing the comments I did see that the dimension type attribute and its uniqueness constraint is no longer needed since measure dimensions have been removed. This has been taken out.

**Comment by dosse** [comment]
@sdmx3mdt Ok.

And yes, I guess that you mean this:

```xml
	<xs:element name="DimensionList" type="DimensionListType" substitutionGroup="ComponentList">
		<xs:annotation>
			<xs:documentation>DimensionList describes the key descriptor for the data structure definition. It is an ordered set of metadata concepts that, combined, classify a statistical series, such as a time series, and whose values, when combined (the key) in an instance such as a data set, uniquely identify a specific series.</xs:documentation>
		</xs:annotation>
		<xs:unique name="SingleMeasureDimension">
			<xs:selector xpath="structure:MeasureDimension"/>
			<xs:field xpath="@type"/>
		</xs:unique>
	</xs:element>
```

**Comment by sdmx3mdt** [comment]
SDMX-JSON structure message updated (previously allowed for several timeDimensions).

**Comment by dosse** [comment]
@sdmx3mdt @jgager In the last TWG it was decided that the single time dimension must always be the last dimension.

Therefor the current choice:

```xml
	<xs:complexType name="DimensionListType">
		<xs:complexContent>
			<xs:extension base="DimensionListBaseType">
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Dimension"/>
					<xs:element ref="TimeDimension"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
```

should be replaced by a sequence. See also https://github.com/glennmdt/sdmx-ml/issues/88
