### ISSUE TITLE
Datastructure: Attribute "assignmentStatus" and Measure "usageStatus" disappeared

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#4]
Will it not be possible anymore to make attributes and measures mandatory or optional?

As a result of the disappeared assignmentStatus and usageStatus, the AttributeUsageStatusType and the UsageStatusType are now orphan and have no usage.  
Also the miss-spelled MeatadataUsageStatusType is orphan and has no usage.

I believe that this property is important and needs to be maintained. However, I would suggest using a simple unique "IsMandatory" boolean property for attributes and measures and a more flexible interpretation: "The isMandatory attribute indicates whether an attribute (or a measure) value must be _available_ for any corresponding existing observation."  
Data messages do not impose anymore sending all mandatory attributes and measures in all messages. Why should a data editor re-submit a data message with all mandatory measures and attributes if only one non-mandatory attribute value is to be changed? That is unnecessarily cumbersome. What only really matters is completeness of the information in an SDMX-compliant data store. This can be achieved during data store update actions through a data completeness validation. Individual data messages however do not always need to be complete.

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Decision: Change agreed to add a a simple unique "IsMandatory" boolean property for attributes and measures
Action: J Gager to update the XML schemas, TF2 to update the information model

**Comment by sdmx3mdt** [comment]
Schemas fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop.

Outstanding action with TF2 to update the IM and Section 2.

**Comment by sdmx3mdt** [comment]
27 July 2021
Alternative solution approved by SDMX TWG to add a new _usage="mandatory|optional_ flag for Data Attributes and Measures, replacing the deprecated _assignmentStatus_ and _usageStatus_.
Details are set out in the attached paper.
[SDMX TWG TF2 - public review issues.docx](https://github.com/sdmx3mdt/public-consultation/files/6892451/SDMX.TWG.TF2.-.public.review.issues.docx)

Outstanding actions:
* TF2 - revise the information model and Section 2
* SDMX-ML schemas team - revise the schemas to add the new _usage_ flag

**Comment by sdmx3mdt** [comment]
AssignmentStatus and UsageStatus replaced by 'usage' attribute.
Attributes
![image](https://user-images.githubusercontent.com/79863147/133432491-091943c5-97e4-41a8-8c92-cf5c2249ff7e.png)
Measures
![image](https://user-images.githubusercontent.com/79863147/133432599-82b03af4-826e-45d3-aa03-49dfdd5e67eb.png)
