### ISSUE TITLE
Rename conneg.md in rest repo to content_negotiation.md 

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#40]
This would really help better finding specific information, since Git(Hub) unfortunately doesn't have a file description.

**Comment by sosna** [comment]
Thanks for reporting this, @dosse. 

The issue has been fixed in the [sdmx30-review-1 branch](https://github.com/sdmx-twg/sdmx-rest/tree/sdmx30-review-1), which will be merged with the rest at the end of the public review process.
