### ISSUE TITLE
REST: Allow wildcarded versions in media types according to SemVer

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#41]
In addition to the new full media types for SDMX 3.0.0 formats, semantic versioning should also apply to media type versions, which will change version numbers much more frequently in the future: Whenever we will make typo corrections or other changes, the version number will change. Users should be able to automatically use newer media type versions when implementers make them available. 

E.g. it should be possible to ask for something like: 

- application/vnd.sdmx.data+json                         to get the currently latest SDMX-JSON data format version available
- application/vnd.sdmx.data+json;version=3        to get the currently latest major SDMX-JSON data format version 3 available
- application/vnd.sdmx.data+json;version=3.1     to get the currently latest minor SDMX-JSON data format version 3.1 available

Original ticket: https://github.com/sdmx-twg/sdmx-rest/issues/147

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Decision - out of scope for version 3.0
