### ISSUE TITLE
REST: Data queries Operators

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#42]
Reported by @eric-basley in https://github.com/sdmx-twg/sdmx-rest/issues/148:

Can you clarify the meaning of ',' separator for c parameter, in develop branch (3.0/data.md) spec:

* c[FREQ]=A,B seems to mean, where FREQ=A **or** FREQ=B (in clause)
* whereas c[TIME_PERIOD]=ge:2020-01,le:2020-12 means TIME_PERIOD >= 2020-01 **and** TIME_PERIOD <= 2020-12

Same separator, 2 meanings depending on operators ?

**Comment by sdmx3mdt** [comment]
Fixed in https://github.com/sdmx-twg/sdmx-rest/tree/sdmx30-review-1
