### ISSUE TITLE
Section 6 - Constraint attachment does not include Data Provider

### ISSUE THREAD

**Issue by agent96** [sdmx3mdt/public-consultation#45]
There  is a bug in section 6 (line 1176)
For a Constraint based on a DSD the Constraint can reference one or more of:

Data Structure Definition
Dataflow
Provision Agreement

**It is missing Data Provider**

**Comment by sdmx3mdt** [comment]
Note that the relevant line is 1993 In the latest SDMX_3-0-0_SECTION_6_DRAFT-1-1-working.doc.

**Comment by sdmx3mdt** [comment]
Missing Data Provider reference added:
![image](https://user-images.githubusercontent.com/79863147/133434785-02d1ddc4-88f6-4bf5-892d-49ed2fa873c2.png)
