### ISSUE TITLE
Constraint Valid From / Valid to on constraining terms

### ISSUE THREAD

**Issue by agent96** [sdmx3mdt/public-consultation#46]
The discussions in the TWG concluded that the constraints members should include an optional valid from and valid to - this was to reduce maintenance of multiple constraints for different time periods - the text alludes to this, but the model and schema need to be updated to reflect this.

**Comment by sdmx3mdt** [comment]
Approved by TWG 27 July 2021 Final Review Meeting.

**Comment by sdmx3mdt** [comment]
Removed SDMX-JSON label because the JSON structure schemas are derived directly from the XML.

**Comment by sdmx3mdt** [comment]
validFrom and validTo added to constraining term.
