### ISSUE TITLE
Review list of artefactTypes in REST structure queries

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#48]
Currently, the following types are defined: datastructure, metadatastructure, categoryscheme, conceptscheme, codelist, hierarchy, hierarchyassociation, valuelist, organisationscheme, agencyscheme, dataproviderscheme, metadataproviderscheme, dataconsumerscheme, organisationunitscheme, dataflow, metadataflow, reportingtaxonomy, provisionagreement, metadataprovisionagreement, structuremap, representationmap, conceptschememap,categoryschememap, organisationschememap, process, categorisation, dataconstraint, metadataconstraint, transformationscheme, rulesetscheme, userdefinedoperatorscheme, customtypescheme, namepersonalisationscheme, vtlmappingscheme

1) "organisationscheme" is an abstract type. It is not explained what type should be returned. I guess that any of agencyscheme, dataproviderscheme, metadataproviderscheme, dataconsumerscheme, organisationunitscheme should be returned. However, this is not clear and also not evident (unless you are an expert of the SDMX IM). 
2) Likewise, what artefact types should be returned when using "codelist"? Should it also return any codelist, hierarchy, hierarchyassociation and valuelist artefacts since all these types are currently listed under the collection "codelists"? Same for "provisionagreement". I don't think that this is meant, thus we have here a logical construction error. 
3) Unlike the abstract type "organisationscheme", there is no parameter option for the types in collection "constraints". There is also no parameter option for the types in "StructureMappings".
4) The type "ReportingTaxonomyMap" is missing.

Linked to issue https://github.com/sdmx3mdt/public-consultation/issues/7, it would be better to remove the abstract type "organisationscheme" from the allowed parameter lists and let the users choose individually the required types by using the OR operator.  Only real types should be listed. This would make things easier understandable.
The list is to be updated to contain all real types.

**Comment by sdmx3mdt** [comment]
@sosna this is for TF4's attention.

**Comment by sdmx3mdt** [comment]
Reviewed by TWG at the 27 July 2021 Public Consultation Final Review Meeting
Decision: TF4 to lead discussions and reach an agreement.

**Comment by sosna** [comment]
The changes are now visible in the [sdmx-rest repository](https://github.com/sdmx-twg/sdmx-rest/tree/sdmx30-review-1).

In a nutshell:
- `organisationscheme` has been removed
- `reportingtaxonomymap` has been added

Point 2 proved to be a non-issue.

Thanks to @dosse for reporting these :)
