### ISSUE TITLE
A complete example for SDMX-ML data messages would be great to understand the new format (e.g. using "comp")

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#49]
The current example in https://github.com/sdmx-twg/sdmx-ml/tree/develop/samples/Structure%20Specific%20Data doesn't have any "none"-level attributes, multiple attribute values or multi-lingual measures, which makes it difficult to judge if the current schema is complete and correct. 

What is the meaning of "DataScopeType"? For which feature is this needed?

**Comment by sdmx3mdt** [comment]
@dosse a Structure Specific Data message sample demonstrating some of the more exotic use cases is being created.

**Comment by sdmx3mdt** [comment]
XML Structure Specific Data sample added in the release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop demonstrating complex array and multi-lingual attributes. 

Additional samples will be added in time for:
* Non-array multi-lingual
* Multiple measures

**Comment by sdmx3mdt** [comment]
Question: What is the meaning of "DataScopeType"? For which feature is this needed?

Answer: DataScopeType is the enumeration for the **dataScope** attribute in the DataSet element of the data message. It is unchanged from version 2.1.

```xml
<message:DataSet ss:dataScope="DataStructure" xsi:type="ns1:DataSetType" ss:structureRef="ECB_EXR_1_0">
        <Series FREQ="A" CURRENCY="CAD" CURRENCY_DENOM="EUR" EXR_TYPE="SP00" EXR_SUFFIX="A" TIME_FORMAT="P1Y" COLLECTION="A" DECIMALS="4" SOURCE_AGENCY="4F0" TITLE="Canadian dollar/Euro" TITLE_COMPL="ECB reference exchange rate, Canadian dollar/Euro, 2:15 pm (C.E.T.)" UNIT="CAD" UNIT_MULT="0">
            <Obs TIME_PERIOD="1999" OBS_VALUE="1.583993822393823" OBS_STATUS="A" />
            <Obs TIME_PERIOD="2000" OBS_VALUE="1.37058431372549" OBS_STATUS="A" />
            <Obs TIME_PERIOD="2001" OBS_VALUE="1.386378740157479" OBS_STATUS="A" />
       </Series>
```

**Comment by dosse** [comment]
Thanks @sdmx3mdt. It seems that DataScopeType only exists in the 2.1 schema but not in the SDMX IM. Since it doesn't bring any additional information on top of the information in the header references and worst it potentially clashes with it, I propose to remove it in https://github.com/sdmx3mdt/public-consultation/issues/52.

**Comment by sdmx3mdt** [comment]
Samples added for complex attributes,
