### ISSUE TITLE
Unpivot Mapping

### ISSUE THREAD

**Issue by javihern98** [sdmx3mdt/public-consultation#55]
On Technical notes, the unpivot mapping (11.3.4.2) behaviour states on line 2708 that "a MeasureDimension component called "measure_name" is added to the SDMX DataStructure", shouldn´t it be adapted to the SDMX 3.0?

Measure Dimensions are also named on the Pivot Mapping (11.3.3.2), but it is stated that is only for SDMX 2.1 compatibility. 
We would like to have more clarification of the use of these two methods on SDMX 3.0

**Comment by stratosn** [comment]
Dear @javihern98 , thanks for reporting that inconsistency. 
Both sections were mainly for 2.1 compatibility, hence adding this explanation in the "Unpivot Mapping" section should make this clear.

Nevertheless, pivoting/unpivoting could also applied to any Dimension in SDMX 3.0, under certain conditions. For example, having a simple Dimension that includes indicators could be such a case, when only one Measure is defined within the DSD.

**Comment by sdmx3mdt** [comment]
Section 6 updated to clarify that the 'unpivot mapping' mainly provides SDMX 2.1 compatibility where the DSD contains a 'measure dimension' or any other dimension acting as a list of measures.
