### ISSUE TITLE
Facet and Facet Type

### ISSUE THREAD

**Issue by javihern98** [sdmx3mdt/public-consultation#56]
On Information Model, the FacetValueType and FacetType are not related at all. 
Theoretically, it is possible to specify a pattern on a boolean value or even a max length on a numeric value, which makes no sense.

A possible solution could be to restrict some facets to type families, for example:

- Number types (short, integer, bigInteger...) can only use the startValue, endValue, isSequence or interval facets
- Boolean type should not use any facet
- "Reporting" types (reportingTimePeriod, reportingYear) should only use date-related facets: startTime, endTime or TimeInterval.

**Comment by sdmx3mdt** [comment]
The joint SDMX Technical and Statistical Working Group decided on 02 September 2021 that the Statistical Working Group will modify the modelling guidelines on the use of facets and facet types after the version 3.0 release to address the issue raised.

**Comment by sdmx3mdt** [comment]
Issue moved to backlog.
