### ISSUE TITLE
Consider ReportingYearEndDay additionally to ReportingYearStartDay

### ISSUE THREAD

**Issue by brainwasher** [sdmx3mdt/public-consultation#58]
related to https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_2_DRAFT-1_0.pdf, page 85:

the class ReportingYearStartDay is currently defined to model a reporting year that starts on a day in the year different to 1st January. In order to be in line with the business requirements described in the "Guidelines on Non-Calendar Year Reporting of Data" https://sdmx.org/?page_id=4345#NonCalendar , the data attributes should also consider reporting years that end on a day different to 31st December. As described in the guidelines in chapter 1 (cases 2b and 4), this is not the same, especially when comparing data across different data providers. Also, the data type of the attribute should be fixed to xs:gMonthDay.

Following implementation of the change request, the guidelines may be simplified.

**Comment by sdmx3mdt** [comment]
Thank you for your comment. However, the consultation period closed on 30 July 2021.

**Comment by dosse** [comment]
@jgager @sdmx3mdt  While reviewing the specs for the ReportingYearStartDay I saw in the XML element description of the dsd component's **conceptRoles** a mention of the attribute "isConceptRole" of the component's concept identity that actually isn't defined anywhere.  Is this attribute missing in the schema or the descriptions are outdated and should be corrected?

**Comment by jgager** [comment]
This seems to be a remnant from something that was changed before 2.1 was finalized. The documentation of ComponentType/ConceptIdentity address this as follows:
>  For components which can specify a concept role, it is implied that the concept which is referenced also identifies a role for the component.

So we can simply remove that from the concept role documentation.
