### ISSUE TITLE
Features / XML attributes of the Annotation class

### ISSUE THREAD

**Issue by brainwasher** [sdmx3mdt/public-consultation#59]
Related to https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_2_DRAFT-1_0.pdf , pages 30-31 and “[Guidelines on the use of the SDMX Annotations](https://sdmx.org/wp-content/uploads/Guidelines-on-the-use-of-SDMX-Annotations.pdf)”.

The identifiers of the Annotations' features are confusing and inconsistent with other parts of the information model at the moment. The way annotations are used currently is described in the linked SWG guidelines document. 
Especially the _id_ attribute leads to confusion. It is only unique within the context of annotations within a single annotated object. 
In reality, we have two types of annotations: controlled vocabulary or ad-hoc custom annotations. A controlled vocabulary is currently defined by the SDMX organisations through the SWG. The controlled vocabulary is maintained as a _Concept Scheme_ in the global registry. Organisaitons may wish to extend this controlled vocabulary or create their own in their own registry.

Thus it is suggested to add an optional reference from the Annotation object to a _Concept_ in a _Concept Scheme_ the same way a DSD component points to a _Concept_ in a _Concept Scheme_ . This will also free up the _title_ attribute for contextual use.
Only for a ad-hoc custom annotations, the _id_ attribute may remain. It should be considered to rename it from _id_ to something else, in order not to confuse its usage of not really being unique outside the context.

**Comment by sdmx3mdt** [comment]
Thank you for your comment. However, the consultation period closed on 30 July 2021.
