### ISSUE TITLE
Remove "sentinelValues" boolean (not required property)

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#6]
It should be sufficient to have the optional "Sentinel" value array, which should be called "SentinelValues".
Indeed, since it's optional, if there is no value array, it means that there are no sentinel values. An additional boolean seems superfluous.

**Comment by sdmx3mdt** [comment]
@dosse does this relate to the XML schemas, the information model, or both? Grateful if you could clarify.

**Comment by dosse** [comment]
@sdmx3mdt This is related to the schemas. 

Also the IM (page 86) is not very clear on this:

| Class | Feature | Description |
| --- | --- | --- |
| SentinelValuesType |  |  A facet that indicates whether an Attribute or a Measure has sentinel values with special meaning, within their data type. |
| SentinelValue |   |  A value that has a special meaning within the representation of its Component | 
|  |  +name | An association of a Sentinel Value to a multilingual name. |
|  |  +description | An association of a Sentinel Value to a multilingual description. |

'SentinelValuesType" seems not only superfluous but even miss-leading, because it's not about a type. I guess this is why is was renamed in the schemas.

It should really be sufficient to just list sentinel values, if there are any. I don't see a need to add another boolean. The simpler, the better.

**Comment by sdmx3mdt** [comment]
TF2 to clarify Section 2 information model specification on Sentinel Values

**Comment by sdmx3mdt** [comment]
Schemas fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop.

Outstanding action with TF2 to update the IM and Section 2.

**Comment by sdmx3mdt** [comment]
27 July 2021
Change approved by the SDMX TWG.
Details are set out in the attached document:
[SDMX TWG TF2 - public review issues.docx](https://github.com/sdmx3mdt/public-consultation/files/6892553/SDMX.TWG.TF2.-.public.review.issues.docx)

Outstanding actions:
* TF2 - revise the information model and Section 2
* SDMX-ML schemas team - revise the schemas to reflect the changes to the information model for Sentinel Values

**Comment by sdmx3mdt** [comment]
SDMX-ML schemas:
sentinelValues boolean removed

Section 2:
sentinelValues boolean removed
