### ISSUE TITLE
Simplify understanding of structure collections through a more coherent naming convention

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#7]
As a developer, it is cumbersome to understand that a ConceptScheme (which contains Concepts) is to be found under the parent "Concepts", while I can find a CategoryScheme (with its Categories) under the parent "Category**Schemes**", since this varying naming approach is not very logical.  
Another example: I can find an Hierarchy under "Hierarchies", but I cannot find a CustomTypeScheme under "CustomTypeScheme**s**". I have to look under "CustomType**s**".  
Etc.  

Could a consistent/coherent naming convention be used for those collections, e.g. always the plural term of the names of the contained artefacts? At least for the new artefacts, this should be easily feasible.

Such a name change represents a major standard change, thus the opportunity to make such housekeeping should not be missed.

**Comment by sdmx3mdt** [comment]
@dosse does this suggestion relate to the information model, or the XML schemas. J generally tries to ensure that the schemas follow the naming as specified in the model.

**Comment by dosse** [comment]
@sdmx3mdt Then I guess that it needs to be addressed in both, IM and schemas. This has always struggled me, and when giving training sessions I was embarrassed to give a reasonable explanation for these inconsistencies. That makes the standard look unfinished.

**Comment by sdmx3mdt** [comment]
16 June 2021 TWG / SWG public consultation public review meeting
Decision: an impact assessment of modifying the information model, the associated technical documentation  (Sections 2, 5 and 6), and the XML schemas is needed before deciding whether the benefit gained justifies the cost of change.
Action: Task Force 2 and J Gager to assess the impact and make a recommendation to the TWG.

**Comment by sdmx3mdt** [comment]
IGNORE - superseded

Proposed revised structure message structure collection naming attached.
[Structure Message Proposed Collection Namings v00a.pdf](https://github.com/sdmx3mdt/public-consultation/files/6861355/Structure.Message.Proposed.Collection.Namings.v00a.pdf)

**Comment by dosse** [comment]
@sdmx3mdt The draft proposal of TF2 has a different list of collection name changes. It splits collections per artefact type because there is no need to group them. This grouping is an unnecessary source of complexity. 

[SDMX TWG TF2 - public review issue #7 - Structure collection naming convention.docx](https://github.com/sdmx3mdt/public-consultation/files/6861775/SDMX.TWG.TF2.-.public.review.issue.7.-.Structure.collection.naming.convention.docx)

**Comment by sdmx3mdt** [comment]
27 July 2021
Revised structure collection naming approved by SDMX TWG.
[SDMX TWG TF2 - public review issue #7 - Structure collection naming convention.docx](https://github.com/sdmx3mdt/public-consultation/files/6893129/SDMX.TWG.TF2.-.public.review.issue.7.-.Structure.collection.naming.convention.docx)

Outstanding actions:
- SDMX-ML schemas team - revise the structure message schemas to reflect the new structure collection naming.

**Comment by sdmx3mdt** [comment]
Structure message collections updated.
