### ISSUE TITLE
Remove "MeatadataUsageStatusType"

### ISSUE THREAD

**Issue by dosse** [sdmx3mdt/public-consultation#9]
in  schemas/SDMXStructureDataStructure.xsd 

"MeatadataUsageStatusType" is incorrectly spelled and seems to be a leftover from the previous metadata approach where some DSD attributes are treated as metadata. This property becomes also unnecessary because the new data formats allow transmitting **any** attribute autonomously without any other measures or attributes and also by including only the necessary dimensions.

**Comment by sdmx3mdt** [comment]
Fixed in release candidate working branch https://github.com/sdmx3mdt/sdmx-ml/tree/develop
